name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install buildozer
        pip install cython

    - name: Build APK
      run: |
        buildozer android release

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: myapp-release
        path: bin/MyApplication-0.1-release.apk